spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TomatoMall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 01260423qian
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
